add ability to use optimisticScenario
gtm-server/json-http-request-tag pull request #5
Opened 2023-06-26 20:03 UTC by dmtsolovey

2023-10-31 17:24 UTC, kHorozhanov commented on template.js
> +        }
There is no call for `data.gtmOnSuccess()` when useOptimisticScenario is turned on

2023-10-31 17:25 UTC, kHorozhanov requested changes
There is no call for data.gtmOnSuccess() when useOptimisticScenario is turned on

2024-11-07 12:56 UTC, gvidoou commented
@kHorozhanov check it pls

2024-11-07 15:27 UTC, Bukashk0zzz approved these changes

2024-11-07 15:31 UTC, kHorozhanov requested changes
Call `gtmOnSuccess` immediately after sending a request

2024-11-12 10:29 UTC, kHorozhanov approved these changes

2024-11-12 10:30 UTC, merged